FROM xanderhendriks/stm32cubeide:16.0

# removed get cmake
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY . .

RUN git submodule update --init --recursive || true

# no hwbuild.bash