name: HW Compile Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hw_compile_debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      # no submodules
      
    - name: Build Docker image
      run: docker build -t stm32-ci -f docker/Dockerfile .

    - name: Build Debug
      run: |
        docker run --rm stm32-ci \
          /workspace/app/hwbuild.bash -c -f "Debug"

  hw_compile_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      # no submodules

    - name: Build Docker image
      run: docker build -t stm32-ci -f docker/Dockerfile .

    - name: Build Release
      run: |
        docker run --rm stm32-ci \
          /workspace/app/hwbuild.bash -c -f "Release"